- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
   - name: sude file
     command: egrep '^[^#]' /etc/sudoers
     register: out
   - debug: var=out.stdout_lines
